server {
    listen 80;
    server_name lab.khld.tech;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name lab.khld.tech;
    ssl_certificate /etc/letsencrypt/live/lab.khld.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lab.khld.tech/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/ {
        proxy_pass http://api:8000/;
    }
}
